### ISSUE TITLE
Uncaught Error: Cannot find module './colors'

### ISSUE THREAD

**Issue by raysarebest** [thedaniel/terminal-panel#15]
I'm writing a jailbreak package for iOS, so I ran `make package install` to automatically build it, `ssh` into my iPhone, and install it, but terminal-paned crashed

**Atom Version**: 0.170.0
**System**: Mac OS X 10.10.2
**Thrown From**: [terminal-panel](https://github.com/thedaniel/terminal-panel) package, v1.8.0

### Stack Trace

Uncaught Error: Cannot find module './colors'

```
At module.js:346

Error: Cannot find module './colors'
  at Module._resolveFilename (module.js:344:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:383:52)
  at Function.Module._load (module.js:286:25)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at createStream (/Users/michael/.atom/packages/terminal-status/node_modules/ansi-html-stream/index.js:18:16)
  at CommandOutputView.module.exports.CommandOutputView.spawn (/Users/michael/.atom/packages/terminal-panel/lib/command-output-view.coffee:223:18)
  at HTMLDivElement.<anonymous> (/Users/michael/.atom/packages/terminal-panel/lib/command-output-view.coffee:62:8)
  at HTMLDivElement.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:115:32)
  at HTMLDivElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDivElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:167:20)

```

### Commands

```
  2x -9:04.3 core:backspace (atom-text-editor.editor)
     -9:01.1 core:save (atom-text-editor.editor)
     -7:11.6 core:paste (atom-text-editor.editor)
  4x -6:47.7 core:backspace (atom-text-editor.editor)
     -6:37.6 core:save (atom-text-editor.editor)
  4x -5:31.0 core:backspace (atom-text-editor#core.ignoredNames.editor.mini)
     -1:07.3 core:confirm (atom-text-editor.editor.mini)
     -0:05.0 terminal-panel:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:00.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".DS_Store"
    ],
    "followSymlinks": true
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v1.2.6
linter, v0.9.1
minimap, v3.5.4
terminal-panel, v1.8.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by braver** [comment]
@raysarebest this is a limited implementation of a terminal, some of the more fancy interactive stuff won't work. I would not expect ssh to work. Crashing is not good of course, but we're limiting the scope of what we want to deal with here, while we're looking for alternative implementations. I'm closing this as a won't fix, unless more similar case prop up.
