### ISSUE TITLE
Uncaught Error: Pane has been destroyed

### ISSUE THREAD

**Issue by pietrondo** [thedaniel/terminal-panel#17]
[Enter steps to reproduce below:]

1. close pannel.

**Atom Version**: 0.174.0
**System**: linux 3.18.2-2-ARCH
**Thrown From**: [terminal-panel](https://github.com/thedaniel/terminal-panel) package, v1.8.0

### Stack Trace

Uncaught Error: Pane has been destroyed

```
At /usr/share/atom/resources/app/src/pane.js:622

Error: Pane has been destroyed
  at Pane.module.exports.Pane.activate (/usr/share/atom/resources/app/src/pane.js:622:15)
  at CommandOutputView.module.exports.CommandOutputView.close (/home/pietro/.atom/packages/terminal-panel/lib/command-output-view.coffee:113:19)
  at HTMLButtonElement.<anonymous> (/usr/share/atom/resources/app/node_modules/space-pen/lib/space-pen.js:181:36)
  at HTMLButtonElement.handler (/usr/share/atom/resources/app/src/space-pen-extensions.js:112:34)
  at HTMLButtonElement.jQuery.event.dispatch (/usr/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLButtonElement.elemData.handle (/usr/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
  9x -9:27.5 core:move-right (atom-text-editor.editor)
     -9:25.6 core:move-left (atom-text-editor.editor)
  5x -9:25.3 core:backspace (atom-text-editor.editor)
  2x -9:22.4 core:move-down (atom-text-editor.editor)
 20x -9:21.7 core:move-left (atom-text-editor.editor)
  3x -9:20.3 core:move-right (atom-text-editor.editor)
     -9:19.4 core:backspace (atom-text-editor.editor)
  2x -9:19.0 core:paste (atom-text-editor.editor)
  2x -9:02.9 core:backspace (atom-text-editor.editor)
  8x -9:01.5 core:move-right (atom-text-editor.editor)
  7x -9:00.3 core:select-left (atom-text-editor.editor)
     -8:59.3 core:select-right (atom-text-editor.editor)
  2x -8:54.5 core:save (atom-text-editor.editor)
     -0:09.6 core:confirm (atom-text-editor.editor.mini)
     -0:00.5 core:move-down (div.settings-view.pane-item)
     -0:00.0 core:move-right (div.settings-view.pane-item)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.21.2
autoclose-html, v0.13.0
color-picker, v1.2.6
linter, v0.10.0
linter-javac, v0.1.3
minimap, v3.5.5
monokai, v0.9.0
terminal-panel, v1.8.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by braver** [comment]
@pietrondo I can't get a solid repro on this. Can you try with the current version? How do you close the pane?

**Comment by szhu** [comment]
Seeing this issue on the current version.

**Comment by braver** [comment]
Yes, I have seen it too, but terminal-panel doesn't do anything with panes. I think its been incorrectly attached to this package. In any case I need more information to act on this.

**Comment by jt3k** [comment]
```
Uncaught Error: Pane has been destroyed
/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:828
Hide Stack Trace
Error: Pane has been destroyed
    at Pane.module.exports.Pane.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:828:15)
    at CommandOutputView.module.exports.CommandOutputView.close (/Users/a.gurtovoy/.atom/packages/terminal-panel/lib/command-output-view.coffee:107:19)
    at CommandOutputView.module.exports.CommandOutputView.open (/Users/a.gurtovoy/.atom/packages/terminal-panel/lib/command-output-view.coffee:97:22)
    at CommandOutputView.module.exports.CommandOutputView.toggle (/Users/a.gurtovoy/.atom/packages/terminal-panel/lib/command-output-view.coffee:116:8)
    at HTMLSpanElement.<anonymous> (/Users/a.gurtovoy/.atom/packages/terminal-panel/lib/cli-status-view.coffee:39:25)

```

atom 1.9.8

**Comment by mattjbones** [comment]
I see this a lot. But I use the terminal-panel with [project-viewer](https://github.com/jccguimaraes/atom-project-viewer) and it's very easy to repro. 

1. Open a project via Project Viewer
2. Start a terminal (I use a watch script but it doesn't look like you need to actually execute a command)
3. Change project via Project Viewer options
4. Attempt to kill / destroy the terminal
5. Error shown above. 

100% reproduction here  Atom 1.10.2, project-viewer 0.3.24 and terminal-panel 1.14.1.

Hope this helps.

**Comment by amunro** [comment]
+1
