### ISSUE TITLE
Uncaught Error: The `::subscribe` method is no longer available on SpacePen views.To store multiple subscription objects for later disposal, add them to a`CompositeDisposable` instance (https://atom.io/docs/api/v0.150.0/CompositeDisposable)and call `.dispose()` on it explicitly in this view's `::detached` hook.

### ISSUE THREAD

**Issue by rnyberg** [thedaniel/terminal-panel#28]
The Ubuntu 14.04 issue was closed as fixed, I updated the plugin but it still does not work.

1. Open new terminal-panel on Ubuntu 14.04

**Atom Version**: 0.174.0
**System**: linux 3.13.0-44-generic
**Thrown From**: [terminal-panel](https://github.com/thedaniel/terminal-panel) package, v1.9.0

### Stack Trace

Uncaught Error: The `::subscribe` method is no longer available on SpacePen views.

To store multiple subscription objects for later disposal, add them to a
`CompositeDisposable` instance (https://atom.io/docs/api/v0.150.0/CompositeDisposable)
and call `.dispose()` on it explicitly in this view's `::detached` hook.

```
At /home/reijo/.atom/packages/terminal-panel/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:576

Error: The `::subscribe` method is no longer available on SpacePen views.

To store multiple subscription objects for later disposal, add them to a
`CompositeDisposable` instance (https://atom.io/docs/api/v0.150.0/CompositeDisposable)
and call `.dispose()` on it explicitly in this view's `::detached` hook.
  at CommandOutputView.View.subscribe (/home/reijo/.atom/packages/terminal-panel/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:576:11)
  at CommandOutputView.module.exports.CommandOutputView.initialize (/home/reijo/.atom/packages/terminal-panel/lib/command-output-view.coffee:32:6)
  at CommandOutputView.View (/home/reijo/.atom/packages/terminal-panel/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at new CommandOutputView (/home/reijo/.atom/packages/terminal-panel/lib/command-output-view.coffee:13:3)
  at CliStatusView.module.exports.CliStatusView.createCommandView (/home/reijo/.atom/packages/terminal-panel/lib/cli-status-view.coffee:27:25)
  at CliStatusView.module.exports.CliStatusView.newTermClick (/home/reijo/.atom/packages/terminal-panel/lib/cli-status-view.coffee:57:6)
  at atom-workspace.atom.commands.add.terminal-panel:new (/home/reijo/.atom/packages/terminal-panel/lib/cli-status-view.coffee:16:33)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:243:29)
  at /usr/share/atom/resources/app/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/usr/share/atom/resources/app/node_modules/command-palette/lib/command-palette-view.js:120:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/usr/share/atom/resources/app/node_modules/go-to-line/node_modules/atom-space-pen-views/lib/select-list-view.js:336:21)
  at space-pen-div.atom.commands.add.core:confirm (/usr/share/atom/resources/app/node_modules/go-to-line/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:243:29)
  at /usr/share/atom/resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app/src/window-event-handler.js:170:20)

```

### Commands

```
  2x -0:11.9 command-palette:toggle (atom-text-editor.editor.mini)
     -0:04.9 core:backspace (atom-text-editor.editor.mini)
  2x -0:02.1 command-palette:toggle (atom-text-editor.editor.mini)
     -0:00.0 core:confirm (atom-text-editor.editor.mini)
     -0:00.0 terminal-panel:new (div.settings-view.pane-item)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".svn",
      "gw"
    ],
    "disabledPackages": [
      "file-icons",
      "livereload",
      "term2",
      "atom-terminal",
      "term"
    ],
    "themes": [
      "seti-ui",
      "seti-monokai"
    ],
    "projectHome": "/home/reijo/projects",
    "autoHideMenuBar": true
  },
  "terminal-panel": {}
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.2.2
atom-color-highlight, v3.0.5
autoclose-html, v0.13.0
autocomplete-plus, v1.1.0
color-picker, v1.4.4
emmet, v2.3.2
file-types, v0.3.0
jshint, v1.2.0
linter, v0.10.0
minimap, v3.5.6
open-last-project, v0.1.1
project-colorize, v0.1.0
project-manager, v1.15.0
project-quick-open, v0.3.0
remember-session, v0.5.1
seti-monokai, v0.3.1
seti-ui, v0.6.1
terminal-panel, v1.9.1

/cc @atom/core

**Comment by braver** [comment]
I'm not getting this. Could you check in the latest version (1.13) if this still occurs?

**Comment by braver** [comment]
This should no longer be an issue and I have not seen new reports.
