### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory '/home/pietro/folder'

### ISSUE THREAD

**Issue by pietrondo** [thedaniel/terminal-panel#36]
1 start a command on terminal pannel

**Atom Version**: 0.184.0
**System**: linux 3.18.6-1-ARCH
**Thrown From**: [terminal-panel](https://github.com/thedaniel/terminal-panel) package, v1.9.2

### Stack Trace

Uncaught Error: ENOENT, no such file or directory '/home/pietro/folder'

```
At fs.js:807

Error: ENOENT, no such file or directory '/home/pietro/Collegamento a biblio'
  at Error (native)
  at fs.statSync (fs.js:807:18)
  at Object.fs.statSync (/usr/share/atom/resources/atom/common/lib/asar.js:155:14)
  at CommandOutputView.module.exports.CommandOutputView._fileInfoHtml (/home/pietro/.atom/packages/terminal-panel/lib/command-output-view.coffee:158:17)
  at /home/pietro/.atom/packages/terminal-panel/lib/command-output-view.coffee:138:25
  at Array.forEach (native)
  at CommandOutputView.module.exports.CommandOutputView.ls (/home/pietro/.atom/packages/terminal-panel/lib/command-output-view.coffee:137:11)
  at space-pen-div.<anonymous> (/home/pietro/.atom/packages/terminal-panel/lib/command-output-view.coffee:55:17)
  at space-pen-div.jQuery.event.dispatch (/usr/share/atom/resources/app/node_modules/jquery/dist/jquery.js:4430:9)
  at space-pen-div.elemData.handle (/usr/share/atom/resources/app/node_modules/jquery/dist/jquery.js:4116:28)
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app/src/window-event-handler.js:182:20)

```

### Commands

```
  2x -2:49.1 core:select-left (atom-text-editor.editor)
     -2:48.5 core:backspace (atom-text-editor.editor)
     -2:47.9 core:move-down (atom-text-editor.editor)
  2x -2:47.7 core:select-right (atom-text-editor.editor)
     -2:47.1 core:backspace (atom-text-editor.editor)
     -2:46.8 core:move-down (atom-text-editor.editor)
     -2:46.6 core:move-right (atom-text-editor.editor)
     -2:46.4 core:select-right (atom-text-editor.editor)
  2x -2:46.1 core:backspace (atom-text-editor.editor)
     -2:45.2 core:move-down (atom-text-editor.editor)
  2x -2:45.0 core:select-right (atom-text-editor.editor)
     -2:44.4 core:backspace (atom-text-editor.editor)
     -0:29.2 core:save (atom-text-editor.editor)
     -0:16.9 terminal-panel:new (atom-text-editor.editor)
  4x -0:10.2 core:backspace (atom-text-editor.editor.mini.is-focused)
  4x -0:07.8 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.21.3
autoclose-html, v0.15.0
color-picker, v1.4.4
grunt-runner, v0.7.0
language-arduino, v0.2.1
linter, v0.12.0
linter-javac, v0.1.3
minimap, v4.3.1
monokai, v0.12.0
terminal-panel, v1.9.2
wakatime, v4.0.0

# Dev
No dev packages
```

**Comment by braver** [comment]
closing this in favour of #47
