### ISSUE TITLE
Uncaught TypeError: Arguments to path.resolve must be strings

### ISSUE THREAD

**Issue by ATNC** [thedaniel/terminal-panel#40]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.186.0
**System**: linux 3.13.0-46-generic
**Thrown From**: [terminal-panel](https://github.com/thedaniel/terminal-panel) package, v1.9.2

### Stack Trace

Uncaught TypeError: Arguments to path.resolve must be strings

```
At path.js:423

TypeError: Arguments to path.resolve must be strings
    at posix.resolve (path.js:423:13)
    at CommandOutputView.module.exports.CommandOutputView.cd (/home/ivan/.atom/packages/terminal-panel/lib/command-output-view.coffee:231:13)
    at space-pen-div.<anonymous> (/home/ivan/.atom/packages/terminal-panel/lib/command-output-view.coffee:119:26)
    at space-pen-div.jQuery.event.dispatch (/opt/atom/resources/app/node_modules/jquery/dist/jquery.js:4430:9)
    at space-pen-div.elemData.handle (/opt/atom/resources/app/node_modules/jquery/dist/jquery.js:4116:28)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
    at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/opt/atom/resources/app/src/window-event-handler.js:182:20)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "solarized-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-django, v0.2.1
linter-jshint, v0.1.0
linter-pep8, v0.1.0
script, v2.18.0
terminal-panel, v1.9.2

# Dev
No dev packages
```

**Comment by braver** [comment]
Could you give some steps to reproduce this?

**Comment by Bernard-Hamann** [comment]
type cd and hit enter

**Comment by rezpe** [comment]
It seems the error happens when the terminal is in a folder that gets removed. Then when entering cd, you get this error. Also, it seems impossible to destroy the terminal.

**Comment by iyerland** [comment]
@rezpe it is easily reproducible even without the condition you mentioned. Its just that the plugin expects an argument of type "string" to be provided with cd! In Linux when you just type "cd" it is assumed to "cd ~" or go back to home directory. In fact "cd ~" works fine! The plugin needs to take care of this condition,

**Comment by rezpe** [comment]
@iyerland, thx for your answer.

**Comment by codekraft-studio** [comment]
I had this error attempting to use __cd__ like __pwd__, in windows console it works without problem but in atom-terminal it expect to have a string passed, so I used

```bash
cd .
```

but I still wonder if is possible to fix it, execute cd command with a default arg if nothing is prompt as argument.. thanks
