### ISSUE TITLE
Uncaught Error: The `::subscribe` method is no longer available on SpacePen views.To store multiple subscription objects for later disposal, add them to a`CompositeDisposable` instance (https://atom.io/docs/api/v0.150.0/CompositeDisposable)and call `.dispose()` on it explicitly in this view's `::detached` hook.

### ISSUE THREAD

**Issue by mattmogford** [thedaniel/terminal-panel#42]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: [terminal-panel](https://github.com/thedaniel/terminal-panel) package, v1.10.0

### Stack Trace

Uncaught Error: The `::subscribe` method is no longer available on SpacePen views.

To store multiple subscription objects for later disposal, add them to a
`CompositeDisposable` instance (https://atom.io/docs/api/v0.150.0/CompositeDisposable)
and call `.dispose()` on it explicitly in this view's `::detached` hook.

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:576

Error: The `::subscribe` method is no longer available on SpacePen views.

To store multiple subscription objects for later disposal, add them to a
`CompositeDisposable` instance (https://atom.io/docs/api/v0.150.0/CompositeDisposable)
and call `.dispose()` on it explicitly in this view's `::detached` hook.
  at CommandOutputView.View.subscribe (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:576:11)
  at CommandOutputView.module.exports.CommandOutputView.initialize (/Users/matt/.atom/packages/terminal-panel/lib/command-output-view.coffee:32:6)
  at CommandOutputView.View (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at new CommandOutputView (/Users/matt/.atom/packages/terminal-panel/lib/command-output-view.coffee:13:3)
  at CliStatusView.module.exports.CliStatusView.createCommandView (/Users/matt/.atom/packages/terminal-panel/lib/cli-status-view.coffee:27:25)
  at CliStatusView.module.exports.CliStatusView.toggle (/Users/matt/.atom/packages/terminal-panel/lib/cli-status-view.coffee:7:3)
  at atom-workspace.atom.commands.add.terminal-panel:toggle (/Users/matt/.atom/packages/terminal-panel/lib/cli-status-view.coffee:17:36)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:246:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:182:20)

```

### Commands

```
     -6:17.2 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-monokai.theme-darkula-ui)
     -6:08.1 core:close (div.deprecation-cop.pane-item.native-key-bindings)
     -6:07.2 application:open (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-monokai.theme-darkula-ui)
     -5:43.3 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-monokai.theme-darkula-ui)
     -1:03.8 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-monokai.theme-darkula-ui)
     -0:48.6 core:copy (div.deprecation-cop.pane-item.native-key-bindings)
     -0:44.9 core:close (atom-text-editor.editor.is-focused)
     -0:00.5 terminal-panel:toggle (div.settings-view.pane-item)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "highlight-line"
    ],
    "themes": [
      "darkula-ui",
      "monokai"
    ],
    "projectHome": "/Users/matt/Documents/Projects/WilliamHill/Colors"
  },
  "terminal-panel": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.4.1
darkula-ui, v0.1.0
javascript-snippets, v1.0.0
jsformat, v0.7.18
jshint, v1.3.0
monokai, v0.12.0
open-last-project, v0.3.4
terminal-panel, v1.10.0

# Dev
No dev packages
```

**Comment by braver** [comment]
Closing in favor of #28
