### ISSUE TITLE
Failed to load the terminal-panel package

### ISSUE THREAD

**Issue by rozzzly** [thedaniel/terminal-panel#46]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.188.0
**System**: Microsoft Windows 8.1
**Thrown From**: [terminal-panel](https://github.com/thedaniel/terminal-panel) package, v1.10.0

### Stack Trace

Failed to load the terminal-panel package

```
At Cannot find module 'underscore-plus'

Error: Cannot find module 'underscore-plus'
  at Module._resolveFilename (module.js:351:15)
  at Function.Module._resolveFilename (C:\Users\Administrator\AppData\Local\atom\app-0.188.0\resources\app\src\module-cache.js:383:52)
  at Function.Module._load (module.js:293:25)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (C:\Users\Administrator\.atom\packages\terminal-panel\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:8:9)
  at Object.<anonymous> (C:\Users\Administrator\.atom\packages\terminal-panel\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:634:4)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (C:\Users\Administrator\AppData\Local\atom\app-0.188.0\resources\app\src\babel.js:162:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (C:\Users\Administrator\.atom\packages\terminal-panel\node_modules\atom-space-pen-views\lib\main.js:4:10)
  at Object.<anonymous> (C:\Users\Administrator\.atom\packages\terminal-panel\node_modules\atom-space-pen-views\lib\main.js:22:4)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (C:\Users\Administrator\AppData\Local\atom\app-0.188.0\resources\app\src\babel.js:162:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (C:\Users\Administrator\.atom\packages\terminal-panel\lib\cli-status-view.coffee:1:10)
  at Object.<anonymous> (C:\Users\Administrator\.atom\packages\terminal-panel\lib\cli-status-view.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (C:\Users\Administrator\AppData\Local\atom\app-0.188.0\resources\app\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (C:\Users\Administrator\.atom\packages\terminal-panel\lib\cli-status.coffee:1:17)
  at Object.<anonymous> (C:\Users\Administrator\.atom\packages\terminal-panel\lib\cli-status.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (C:\Users\Administrator\AppData\Local\atom\app-0.188.0\resources\app\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Package.module.exports.Package.requireMainModule (C:\Users\Administrator\AppData\Local\atom\app-0.188.0\resources\app\src\package.js:678:34)
  at C:\Users\Administrator\AppData\Local\atom\app-0.188.0\resources\app\src\package.js:189:28
  at Package.module.exports.Package.measure (C:\Users\Administrator\AppData\Local\atom\app-0.188.0\resources\app\src\package.js:167:15)
  at Package.module.exports.Package.load (C:\Users\Administrator\AppData\Local\atom\app-0.188.0\resources\app\src\package.js:181:12)
  at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\Administrator\AppData\Local\atom\app-0.188.0\resources\app\src\package-manager.js:383:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Administrator\AppData\Local\atom\app-0.188.0\resources\app\src\package-manager.js:460:30)
  at C:\Users\Administrator\AppData\Local\atom\app-0.188.0\resources\app\node_modules\settings-view\lib\package-manager.js:268:29
  at exit (C:\Users\Administrator\AppData\Local\atom\app-0.188.0\resources\app\node_modules\settings-view\lib\package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (C:\Users\Administrator\AppData\Local\atom\app-0.188.0\resources\app\src\buffered-process.js:63:47)
  at C:\Users\Administrator\AppData\Local\atom\app-0.188.0\resources\app\src\buffered-process.js:77:18
  at Socket.<anonymous> (C:\Users\Administrator\AppData\Local\atom\app-0.188.0\resources\app\src\buffered-process.js:150:18)
  at Socket.emit (events.js:138:20)
  at Pipe.close (net.js:477:12)

```

### Commands

```
  2x -2:52.7 core:backspace (atom-text-editor.editor.mini)
     -2:47.7 core:confirm (atom-text-editor.editor.mini)
     -1:14.0 pane:reopen-closed-item (div.settings-view.pane-item)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "one-dark-syntax"
    ],
    "followSymlinks": true
  }
}
```

### Installed Packages

```coffee
# User
atom-typescript, v1.8.0
autocomplete-css, v0.6.0
autocomplete-emojis, v1.0.0
autocomplete-html, v0.5.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.6.0
autocomplete-plus-async, v0.22.0
autocomplete-snippets, v1.2.0
color-picker, v1.5.0
compare-files, v0.4.1
crosshairs, v0.1.2
filesize, v0.2.0
font-awesome-snippetset, v0.0.6
function-name-in-status-bar, v0.2.6
git-tab-status, v1.6.0
language-apache, v1.2.0
language-batchfile, v0.3.0
language-gitignore, v0.1.1
less-than-slash, v0.4.2
linter, v0.12.0
minimap, v4.6.0
minimap-bookmarks, v0.1.0
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.2
next-scribe, v0.1.0
seti-ui, v0.6.3
ssh-config, v0.10.0
terminal-panel, v1.10.0
text-manipulation, v0.4.0
useful-context-menu, v0.2.1
vnc, v0.1.3
windows-context-menu, v0.3.1

# Dev
No dev packages
```

**Comment by braver** [comment]
> Error: Cannot find module 'underscore-plus'

This is probably in the wrong package
