### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory '/Users/michael/.Xresources'

### ISSUE THREAD

**Issue by mikeLspohn** [thedaniel/terminal-panel#47]
[Enter steps to reproduce below:]

1. I installed plugin on Mac OSX Yosemite 
2. Restarted atom and keybinding shift + enter doesn't work so I tried the little terminal button at the bottom and got this error when running a command.

**Atom Version**: 0.188.0
**System**: Mac OS X 10.10.2
**Thrown From**: [terminal-panel](https://github.com/thedaniel/terminal-panel) package, v1.10.0

### Stack Trace

Uncaught Error: ENOENT, no such file or directory '/Users/michael/.Xresources'

```
At fs.js:807

Error: ENOENT, no such file or directory '/Users/michael/.Xresources'
  at Error (native)
  at fs.statSync (fs.js:807:18)
  at Object.fs.statSync (ATOM_SHELL_ASAR.js:206:16)
  at CommandOutputView.module.exports.CommandOutputView._fileInfoHtml (/Users/michael/.atom/packages/terminal-panel/lib/command-output-view.coffee:158:17)
  at /Users/michael/.atom/packages/terminal-panel/lib/command-output-view.coffee:138:25
  at Array.forEach (native)
  at CommandOutputView.module.exports.CommandOutputView.ls (/Users/michael/.atom/packages/terminal-panel/lib/command-output-view.coffee:137:11)
  at space-pen-div.<anonymous> (/Users/michael/.atom/packages/terminal-panel/lib/command-output-view.coffee:55:17)
  at space-pen-div.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:4430:9)
  at space-pen-div.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:4116:28)
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:180:20)

```

### Commands

```
     -0:22.2 editor:newline-below (atom-text-editor.editor.vim-mode.command-mode)
  2x -0:21.1 editor:newline (atom-text-editor.editor.vim-mode.command-mode)
     -0:19.4 vim-mode:activate-insert-mode (atom-text-editor.editor.vim-mode.command-mode)
     -0:19.0 editor:newline (atom-text-editor.editor.vim-mode.command-mode)
     -0:17.3 vim-mode:activate-command-mode (atom-text-editor.editor.vim-mode.command-mode)
     -0:15.9 editor:newline (atom-text-editor.editor.vim-mode.command-mode)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "solarized-dark-syntax"
    ]
  },
  "terminal-panel": {}
}
```

### Installed Packages

```coffee
# User
linter, v0.11.1
terminal-panel, v1.10.0
vim-mode, v0.31.0

# Dev
No dev packages
```

**Comment by braver** [comment]
Is there something special in your environment or .bash_profile, or anything else that might cause this?

**Comment by mikeLspohn** [comment]
Well tgat is the oath for the directory on my machine (macbook pro osx) so
the path wpuld need to be changed on a different computer. Also none of my
setup has been tested on linux or windows yet.

**Comment by mikeLspohn** [comment]
Sorry about that im on a new phone and the spellings not quite smart yet. Ill look at this when I am on my computer.
