### ISSUE TITLE
Failed to activate the terminal-panel package

### ISSUE THREAD

**Issue by developit** [thedaniel/terminal-panel#49]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.190.0
**System**: Mac OS X 10.10.2
**Thrown From**: [terminal-panel](https://github.com/thedaniel/terminal-panel) package, v1.10.0

### Stack Trace

Failed to activate the terminal-panel package

```
At undefined is not a function

TypeError: undefined is not a function
    at Object.module.exports.activate (/Users/developit/.atom/packages/terminal-panel/lib/cli-status.coffee:18:30)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:225:19)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:206:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:152:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:199:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:435:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:419:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app/src/config.js:302:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:414:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:395:46)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "disabledPackages": [
      "autoflow",
      "minimap",
      "autosave",
      "background-tips",
      "dev-live-reload",
      "feedback",
      "metrics",
      "styleguide",
      "welcome",
      "archive-view",
      "autocomplete",
      "bookmarks",
      "deprecation-cop",
      "exception-reporting",
      "git-history",
      "git-log",
      "git-plus",
      "git-tab-status",
      "atom-jshint",
      "merge-conflicts",
      "package-generator",
      "update-package-dependencies",
      "travis-ci-status",
      "jshint",
      "linter-eslint",
      "linter",
      "linter-jshint",
      "wrap-guide"
    ],
    "themes": [
      "spacegray-dark-ui",
      "spacegray-dark-syntax"
    ],
    "audioBeep": false
  },
  "terminal-panel": {
    "WindowHeight": 100
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v1.6.0
resize-panes, v0.1.0
spacegray-dark-syntax, v0.2.0
spacegray-dark-ui, v0.8.0
terminal-panel, v1.10.0
visual-bell, v1.0.0

# Dev
No dev packages
```

**Comment by braver** [comment]
I need more info to work in this. Are you still getting this error?

**Comment by andya9** [comment]
Yes, the bug is still there in atom 198 (linux too)

**Comment by andya9** [comment]
The bug only happens in 1.0 api preview; so it should be related to this deprecation, as shown by deprecation cop:
          Use PackageManager::onDidActivateInitialPackages instead

**Comment by braver** [comment]
Oh, that helps! Terminal-panel isn't 1.0 ready yet, we're working on that. There are a number of open issues with regards to the deprecations, so I'm closing this if it's only in 1.0-mode.
