### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, scandir 'atom://config'

### ISSUE THREAD

**Issue by mKarpis** [thedaniel/terminal-panel#82]
[Enter steps to reproduce below:]

1. install + restart
2. created new terminal
3. tried 'ls'

**Atom Version**: 1.0.6
**System**: Mac OS X 10.10.4
**Thrown From**: [terminal-panel](https://github.com/thedaniel/terminal-panel) package, v1.14.1

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, scandir 'atom://config'

```
At fs.js:805

Error: ENOENT: no such file or directory, scandir 'atom://config'
  at Error (native)
  at Object.fs.readdirSync (fs.js:805:18)
  at Object.fs.readdirSync (ATOM_SHELL_ASAR.js:441:28)
  at CommandOutputView.module.exports.CommandOutputView.ls (/Users/eDS/.atom/packages/terminal-panel/lib/command-output-view.coffee:132:16)
  at atom-text-editor.atom.commands.add.core:confirm (/Users/eDS/.atom/packages/terminal-panel/lib/command-output-view.coffee:51:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
     -0:22.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:04.3.0 terminal-panel:new (atom-text-editor.editor.is-focused)
  2x -0:00.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "whitespace"
    ]
  },
  "terminal-panel": {}
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.11
language-fortran, v1.5.6
terminal-panel, v1.14.1

# Dev
No dev packages
```

**Comment by rdooh** [comment]
I had a similar issue, for which the solution was to make sure that the Atom config directory was not my primary project folder.  This happens if you had just opened Atom fresh and then play around with system settings.  In my case, closing this folder (Remove Project Folder) did the trick.
