### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by Ardaq** [thedaniel/terminal-panel#86]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Ubuntu 14.04.3
**Thrown From**: [terminal-panel](https://github.com/thedaniel/terminal-panel) package, v1.14.1

### Stack Trace

Uncaught TypeError: Path must be a string. Received undefined

```
At path.js:8

TypeError: Path must be a string. Received undefined
  at assertPath (path.js:8:11)
  at posix.resolve (path.js:413:5)
  at CommandOutputView.module.exports.CommandOutputView.cd (/home/ardaq/.atom/packages/terminal-panel/lib/command-output-view.coffee:120:11)
  at atom-text-editor.atom.commands.add.core:confirm (/home/ardaq/.atom/packages/terminal-panel/lib/command-output-view.coffee:49:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:243:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:528:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:351:22)
  at HTMLDocument.module.exports.WindowEventHandler.handleDocumentKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:97:20)

```

### Commands

```
     -0:03.8.0 terminal-panel:toggle (atom-text-editor.editor.is-focused)
     -0:01.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-django, v0.3.0
autocomplete-css, v0.11.0
color-picker, v2.0.13
django-templates, v0.5.0
django-test-runner, v0.3.0
javascript-snippets, v1.0.0
language-cpp14, v0.4.2
language-python, v0.41.0
language-python-django-templates, v0.1.0
linter, v1.10.0
linter-flake8, v1.9.1
linter-gcc, v0.3.9
minimap, v4.16.0
python-autopep8, v0.1.3
python-tools, v0.6.5
terminal-panel, v1.14.1

# Dev
No dev packages
```

**Comment by alirezaafzalaghaei** [comment]
i wrote "cd" to get current path!
