### ISSUE TITLE
Enabling terminal-panel package breaks fuzzy-finder

### ISSUE THREAD

**Issue by sirianni** [thedaniel/terminal-panel#91]
I noticed the following exception when opening the fuzzy-finder window:
```
Cannot find module 'atom' Error: Cannot find module 'atom'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/fuzzy-finder/lib/load-paths-handler.js:12:19)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/fuzzy-finder/lib/load-paths-handler.js:180:4)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/task-bootstrap.js:110:13)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/task-bootstrap.js:112:4)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at [eval]:2:1
    at Object.exports.runInThisContext (vm.js:54:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:434:26)
    at node.js:578:27
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)

Cannot read property 'bind' of null TypeError: Cannot read property 'bind' of null
    at process.<anonymous> (/usr/share/atom/resources/app.asar/src/task-bootstrap.js:82:23)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:685:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)
```

The error does not occur in safe mode.  After much trial and error of enabling/disabling individual packages, I've narrowed the problematic package down to `terminal-panel`.  I'm not sure what side-effect of terminal panel could be causing such an error in fuzzy-finder.

See https://github.com/atom/fuzzy-finder/issues/100 for a similar situation.

**Comment by sirianni** [comment]
Also see https://github.com/nickclaw/atom-grunt-runner/issues/48
Since `grunt-runner` and `terminal-panel` are both forking external processes, perhaps that gives a clue as to the root cause...?
